[tool.mypy]
warn_unused_configs = true
python_version = "3.10"
mypy_path = ["src/py", "pyodide-build"]
check_untyped_defs = true
show_error_codes = true

[[tool.mypy.overrides]]
module = [
  "_pyodide_core",
  "docutils.parsers.rst",
  "js",
  "pyodide_js",
  "pytest",
  "ruamel.yaml",
  "matplotlib.*",
  "PIL.*",
]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
  "micropip.externals.*",
]
check_untyped_defs = false

[tool.pycln]
all = true

[tool.isort]
profile = "black"
known_first_party = [
  "pyodide",
  "pyodide_js",
  "micropip",
  "pyodide_build",
  "_pyodide",
]
known_third_party = [
  "build",
]
