[tool.mypy]
warn_unused_configs = true
python_version = "3.9"
mypy_path = "src/py"
check_untyped_defs = true

[[tool.mypy.overrides]]
module = [
  "_pyodide_core",
  "docutils.parsers.rst",
  "js",
  "pyodide_js",
  "pytest",
  "ruamel.yaml",
]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
  "micropip.externals.*",
]
check_untyped_defs = false

[tool.pycln]
all = true

[tool.isort]
profile = "black"
known_first_party = [
  "pyodide",
  "pyodide_js",
  "micropip",
  "pyodide_build",
  "_pyodide",
]


[tool.pytest.ini_options]
minversion = "6.0"
norecursedirs = [
  "build",
  "cpython",
  "emsdk",
  ".artifacts",
]
addopts = [
  "--doctest-modules",
  "--ignore='packages/matplotlib/src'",
  "--strict-markers",
  "--strict-config",
]
markers = [
  "skip_refcount_check: Dont run refcount checks",
  "skip_pyproxy_check: Dont run pyproxy allocation checks",
  "driver_timeout: Set script timeout in WebDriver",
]
testpaths = [
  "src",
  "pyodide-build",
  "packages",
]
filterwarnings = [
  "error",
  "ignore:desired_capabilities has been deprecated, please pass in an Options object with options kwarg:DeprecationWarning",
  "ignore:Raising unittest.SkipTest to skip tests:pytest.PytestRemovedIn8Warning",
]
log_cli_level = "info"
xfail_strict = true
asyncio_mode = "auto"
